### ISSUE TITLE
Please add a "read-only" flag to the XML files.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#101]
**Is your feature request related to a problem? Please describe.**
Bug #100 inadvertently caused overwriting of an example network file. I'd like to avoid such mishaps.

**Describe the solution you'd like**
This is a non-trivial feature, that would work like this:
1. loaded network gets a "Read-only" checkbox that is set like the value in the XML file was.
2. a new network gets "Read-only" unchecked, as read-only and empty is an invalid combination.
3. Upon save, check if the target file exists. If not, save the file with its current "Read-only" value.
4. If the file exists, compare the "Read-only" in the file to the "Read-only" checkbox.
5. If the checkbox shows different from the file, write the file regardless because the user changed the status.
6. If the file and checkbox are the same, only write the file if the file has its "Read-only" flag false.

**Describe alternatives you've considered**
You could instead change the file attributes to make a file read-only, but then changing it would become more difficult. 

**Additional context**

**Comment by FutureAIGuru** [comment]
Apparently I didn’t think this through carefully enough…
Let’s go back to the old way of installing the library files directly beneath the .exe folder. That way, the program will know where the library networks are if they exist and they will be RO.
Now, all I have to do is make the program properly handle RO files. All programs should be able to do that anyway.
Finally, I need a default directory for the program to save things—but the user can do whatever they want.

**Comment by Moorelife** [comment]
True, there actually is no need to open a file as "read and write" once you load it. Just open for read, read and close again.
Then at save time try to open for writing, and cancel if you get an open error. 
As for a default save location, I am pretty sure you can request the documents folder from Windows, and create a subfolder there.
Or even better for users (not everyone uses Documents), let the user set a default location for their networks.

**Comment by Moorelife** [comment]
I will change the Installer to the way it was before, and we'll keep the other bug open for it. this can just be closed then.

**Comment by FutureAIGuru** [comment]
Here are the changes I’ve made but haven’t checked it yet…

  1.  You can open a RO file.
  2.  If you are editing a RO file the Save command and Save button are disabled…you must use saveAs.
  3.  If you try to save to a RO file, you get an error message and a graceful exit.

My remaining open item:
The first time you try to Save (with a new file) or SaveAs with a library file with changes, what should the default directory be? Would documents/bransim be OK? Then I’d need to create the folder regardless of what the user did on installation and whether he wanted it. If I don’t have a default directory, users will stuff files wherever and may not be able to find them. What do you think?

**Comment by FutureAIGuru** [comment]
also, if you are editing a RO file, there is no prompt to save changes.

**Comment by Moorelife** [comment]
The above handling makes this no longer needed.
