### ISSUE TITLE
Dragging Module2DModel across Module2DSim hijacks barrier cells.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#102]
**Describe the bug**
When Module2DModel is dragged across a Module2DSim with barrier synapses set, these get hijacked by the Module2DModel.

**Application**: Brain Simulator

**Module/Network**: Possibly all modules.

**To Reproduce**
1. Create a Module2DSim.
2. Draw some synapses on it.
3. Create a Module2DModel next to it.
4. Drag the Module2DModel over the Module2DSim so it goes over the neurons connected by synapses.
5. Notice the cells being picked up by the drag, and made part of the Module2DModel.

**Expected behavior**
Modules should be atomic components, that cannot be dragged apart in this way.
I have a feeling modules and selections being dragged should temporarily be copied to 
an isolated network, so their cells do not interact with cells they get dragged over.

**Screenshots**
Before drag and drop:
![IMG_20210421_122229](https://user-images.githubusercontent.com/11266191/115539876-ca263980-a29d-11eb-8e7c-5f94ab9d82ba.png)

After drag and drop:
![IMG_20210421_122247](https://user-images.githubusercontent.com/11266191/115539919-d4483800-a29d-11eb-8dda-ab6ce8ad8099.png)

**Desktop (please complete the following information):**
 - OS: 
 - Version [v0.9a]

**Comment by FutureAIGuru** [comment]
I can make modules act like selections so they prevent moving across other neurons which are in use.

**Comment by Moorelife** [comment]
Well, you actually should be able to move them across existing neurons, but they should not be picking up stuff...  :-)

**Comment by FutureAIGuru** [comment]
I agree with you but the code isn’t written that way now and it would be a biggish deal to make it work. So, it’s a bang-for-the-buck question.
I can make it not screw up existing neurons pretty easily. Making it work the “right” way is a complete rewrite of the module/selection dragging process which is a bit fragile at the moment.

**Comment by Moorelife** [comment]
Maybe leave this open for later then....
