### ISSUE TITLE
Zooming and scrollbars should have sensible limits.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#103]
**Describe the bug**
At current, two things are slightly frustrating:
Scroll bars on the neuron window far exceed the boundaries of the effective network.
Zoom factors are unlimited in both directions, and eventually crash the program!

**Application**: Brain Simulator

**Module/Network**: (if *your* network, please attach XML file)

**To Reproduce**
1. Create a new network of some size.
2. Zoom out so you have grey area on all sides.
3. Notice scroll bars allow you to move the network completely off screen in any direction.
4. Zoom in or out, as far as it will go. 
5. Notice uselessness of display, and eventually a crash in both directions.

**Expected behavior**
- Well-behaved scroll bars should only scroll until the end of the active area, and no further.
- Their sizes should reflect the proportion of visible / possible.
- Zooming should only be allowed until some useful value is reached either way:
- Zooming in or out to what the new zoom button will toggle between seems to indicate the two limits.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Winodws 10 Pro  20H2
 - Version: 2021-04-21 master

**Comment by FutureAIGuru** [comment]
Zooming out is now limited so that the minimum size will display twice the maximum array extend.

**Comment by Moorelife** [comment]
Zooming IN still crashes the program, and I think a max zoom in should maybe leave 3x3 neurons on screen. Any further is hardly useful.

**Comment by Moorelife** [comment]
Max zoom set to 300 works wonders.
