### ISSUE TITLE
When opening a new network on a live one, the save prompt disrupts the firing pattern on screen.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#111]
**Describe the bug**
When I try to open a new network with BasicNeurons open, the firing of neurons noticeably changes right after the "Save old network" prompt opens.

**Application**: Brain Simulator

**Module/Network**: at least BasicNeurons, possibly others.

**To Reproduce**
1. Open BasicNeurons.
2. Notice the firing pattern of subpattern number 8.
3. Click "Open" again, watch save prompt come up.
4. Notice no firing in subpattern number 8.
5. Cancel saving, partial firing pattern remains.

Simpler scenario:
1. Open BasicNeurons.
2. Notice the firing pattern the network.
3. Click the close icon top left of the window
4. Notice save prompt comes up, firing pattern almost gone.
5. Cancel saving, partial firing pattern remains.

So behavior of network changed from a canceled save. It looks like all charges were reset before save prompt was shown.

**Expected behavior**
Shouldn't the charges right before the save prompt also be saved?

**Screenshots**
![IMG_20210423_075435](https://user-images.githubusercontent.com/11266191/115826716-a08b2080-a40b-11eb-8cb3-c74d8b682a1e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version: 2021-04-23 master

**Comment by FutureAIGuru** [comment]
I think this is a more specific example of #107

**Comment by Moorelife** [comment]
Might be, but it is a highly visible one...

**Comment by Moorelife** [comment]
Another highly visible one is this:
Clicking Save on a network like BasicNetwork seems to keep it in a state where it is still running, 
Whereas Clicking Open, answering yes to the save prompt and then reloading the same network disrupts it.
