### ISSUE TITLE
Add try/catch blocks around all calls into module code

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#121]
**Describe the bug**
Any uncaught exception in a module will crash the brain simulator

**Application**: Brain Simulator, 

**To Reproduce**
1. Edit program code in a module to create an uncaught exception
2. Include module on a network
3. BrainSim Crashes

**Expected behavior**
Either an error messageBox or similar 
This can occur on Fire, Initialize settupBeforeSave SetupAfterLoad

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Version [v0.9a]

**Comment by Moorelife** [comment]
Given the behavior of the latest master, has this been fixed? I think so...

**Comment by Moorelife** [comment]
Yup, no problem anymore.
