### ISSUE TITLE
Putting mouse in main menu before initialization is complete crashes

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#122]
**Describe the bug**
Putting mouse in main menu before initialization is complete crashes

**Application**: Brain Simulator,

**To Reproduce**
1. Start the program 
2. Before the neuron array is displayed, put mouse in vicinity of mainmenu
3. Crash

The problem is that some of the parameters in the main menu require querying the NeuronEngine before it has been initialized.

**Comment by Moorelife** [comment]
This problem is apparently now fixed....
