### ISSUE TITLE
File opened from Recent and not found should be removed from recent.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#128]
**Describe the bug**
A file you are trying to reload via File => Recent and the message box comes up saying part of the path or the file itself can't be found, the entry in File => Recent should be removed so as to avoid confusion for the user. 

**Application**: Brain Simulator

**Module/Network**: N/A

**To Reproduce**
1. Copy an example network to a new location somewhere.
2. Open it with Brain Simulator II.
3. Load another network.
4. Remove the copied file.
5. Choose File => Recent and try to reload the first network.
6. This gives either a file not found or path not found error.
7. Choose File => Recent again, notice entry still remains.

**Expected behavior**
I expect files that are no longer existing to be removed from recent files.
This can happen in two distinct ways:
- When a file fails to load, remove it from the list.
- Or better: when opening the recent sub menu, check each entry for existence, and skip those who no longer do.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Winodws 10 Pro  20H2
 - Version: 2021-04-24 master

**Comment by Moorelife** [comment]
Change is in, needs to be verify as functioning.

**Comment by FutureAIGuru** [comment]
I’ll check it out

**Comment by Moorelife** [comment]
Tested this several times, works fine now as implemented.
