### ISSUE TITLE
Please make neuron popup menu more clear.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#131]
**Is your feature request related to a problem? Please describe.**
The 'Apply to all Neurons' checkbox has been kind of added to the neuron popup menu as an afterthought.
But some menu items can simply never be used sensible in an 'all neurons' setting.

**Describe the solution you'd like**
Split the menu into several sections:
- First, 'Apply to All Neurons' should only exist if there is a selection.
- All items that cannot be applied across the selection but refer to the neuron that was right-clicked.
- All items that can be applied across the selection, and will do so if 'Apply to All Neurons' is checked.
- Also, 'Clear' is a very imprecise command. Make it 'Clear Synapses' to make sure what happens.
- Make the menu narrower to avoid the user having to mouse far right to get to the sub menus.

**Describe alternatives you've considered**
None considered.

**Additional context**
Screenshot of what the popup menu might look like:
![New Neuron Popup Menu](https://user-images.githubusercontent.com/11266191/115969518-96693f00-a53d-11eb-8b50-7a2897af172c.jpg)

**Comment by Moorelife** [comment]
Am I missing something or did you get rid of the "Apply to all Neurons" checkbox? Surely you still want the user to be able to control whether info changed in the lower section pertains to just the right-clicked neuron or all in the selection?

**Comment by Moorelife** [comment]
Oops, my bad, didn't have a selection.

**Comment by FutureAIGuru** [comment]
We might prefer to show the checkbox always but enable it only if there is a selection.

**Comment by Moorelife** [comment]
Makes perfect sense, Charlie. That way users get warned they have no selection
