### ISSUE TITLE
Occasional Crash on open with "Rows" not initialized

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#140]
**Describe the bug**
Really sketchy but if you try hard to crash the system on startup there are several possible falures. We should keep an eye on this.

**Application**: Brain Simulator, Neuron Engine, 

**To Reproduce**
1. Start the program
2. While the splash screen is still up OR file is still loading
3. Try doing things, menu, mouse, keyboard
4. program crashes.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Version [v0.9a]

**Comment by Moorelife** [comment]
This is exactly why I advocate to keep the engine in a stopped state during loads, saves, random synapses, mutual suppression, etc. 
Also, make the corresponding dialogs and progress bar at least 'program modal' because now they have a habit of getting hidden behind the main window, leaving the user with just a beep whenever the main window is clicked.

**Comment by Moorelife** [comment]
Possibly related are #137, #135, maybe #126?

**Comment by FutureAIGuru** [comment]
The way you are addressing this is absolutely correct. In the code, Load, Save, etc. are entirely within the scope of SuspendEngine and ResumeEngine. So the engine should be stopped for these actions.

I think the problem is related to the addition of the progress dialog which lets things proceed when they should not. This is also the culprit in starting a second RandomNeurons function while the first is still in progress e.g..

**Comment by Moorelife** [comment]
I've rewritten the simple check for IsArrayEmpty(), that tackles the following:
- is the array null?
- is the array size 0?
- is the row count 0?
- is the column count 0?
This should at least avoid any situations where a partial check was done before.

**Comment by Moorelife** [comment]
Have not seen this happen since previous comment.
