### ISSUE TITLE
Add a method for setting up firewall

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#141]
I'll make this a separate .exe.  It will 
upgrade itself to run-as admin 
Check to see if the firewall rules are already in place
Add the necessary inbound and outbound rules

- Inbound to BrainSim (ports?)
- Outbound from BrainSim
- Inbound to NeuronServer (Ports?) 
- Outbound to NeuronServer
-

**Comment by Moorelife** [comment]
Make sure it is properly documented as to what it does. Users are a bit shy when it comes to programs requiring elevation. 
Maybe write out the actions undertaken to the console as they happen.

**Comment by Moorelife** [comment]
This would also fix #38 possibly.

**Comment by Moorelife** [comment]
So far it does not seem to fix anything, according to the following scenario:
- Run SetupFireWall as administrator, answer Y to all prompts.
- Start a NeuronServer, either on the same or another machine.
- Start Brain Simulator II, choose New Network.
- Check Use Servers box, see 'No Servers Detected'.
- Click Refresh, still no servers.

**Comment by Moorelife** [comment]
This bug has been solved now...
