### ISSUE TITLE
Setting tooltip with selection doesn't work

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#145]
**Describe the bug**
Setting a tooltip on a selection clobbers the existing labels of neurons in the selection

**Application**: Brain Simulator, Neuron Engine, 

**To Reproduce**
1. create selection
2. Add label to neurons in selection
3. Notice they are auto-incremented
4. Set a tooltip to a neuron in the selection
5. Notice that the labels are no longer correct (although the tooltips are correct)

**Expected behavior**
Labels should be unchanged if tooltip is changed

**Comment by Moorelife** [comment]
Agreed this way of doing things makes the problem go away.
