### ISSUE TITLE
Installer should automatically start program on completion

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#148]
**Is your feature request related to a problem? Please describe.**
Installer should automatically start program on completion

**Describe the solution you'd like**
Perhaps optional with a checkbox (but this isn't necessary)

**Comment by Moorelife** [comment]
The latest and greatest should present you with an option to launch the program immediately after install.

**Comment by Moorelife** [comment]
This works properly now, so closing the issue.
