### ISSUE TITLE
Random Synapses appears to no longer be working. 

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#149]
**Describe the bug**
I can select any set of neurons, but asking for 'Random Neurons' or 'Mutual Suppression' seems to have no effect other than checking the All Neurons box.

**Application**: Brain Simulator

**Module/Network**: N/A

**To Reproduce**
1. Create new empty network.
2. Select an area in it.
3. Right Click and Choose either 'Random Synapses' or 'Mutual Suppression'.
4. Notice neither works, although synapses should be visible.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Version [v0.9a]

**Comment by Moorelife** [comment]
I must have been seeing things, this appears to be working fine now I checked again.

**Comment by FutureAIGuru** [comment]
There was an issues in the Progress Bar. If you ever passed it an empty string for a label, it considered that to be a cancel.
Now, only a 100% entry can cancel the progress bar programmatically.
That fixed the random synapses but it may have broken the pogress bar elsewhere.

**Comment by Moorelife** [comment]
Thanks for the info, I'll have an eye out for trouble in that area.
