### ISSUE TITLE
Crash with engine suspend/resume issue

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#152]
**Describe the bug**
Crash on load file. The load file request is directly after the SuspendEngine call but the engine thread was running calling HandleProgrammedActions. and the engineDelay was 500. Perhaps the background process which loads the file allows a resume too soon.

This may be repeatable. I have two networks, ratedecoder and ratedecoder2.  Using the "Recent" menu, I flip back and forth between the two. After a few tries, I get a crash where the engine is running when it should be suspended.

A similar crash may occur of the display updates. It calls for neurons from the engine and these no longer exist.

**Comment by Moorelife** [comment]
This indeed has been fixed by the added stack for suspends and resumes.
