### ISSUE TITLE
New Module doesn't check for minimums outside array boundaries

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#153]
**Describe the bug**
When you create a new module, it is automatically expanded based on the minWidth and minHeight. Unfortunately, the expansion doesn't check to see if the module would extend past the edge of the neuron array which causes a crash.

**Application**: Brain Simulator, 

**Module/Network**: (if *your* network, please attach XML file)

**To Reproduce**
1. Create a 2x2 selection at the bottom edge of the array
2. Convert the selection to a ColorComponent module which has a minHeight of 5
3. Crash

**Expected behavior**
Perhaps move the module so it fits, perhaps put up an error and quit.

**Comment by Moorelife** [comment]
This is indeed fixed.
