### ISSUE TITLE
Loading 3DSim after SimVision hangs Brain Simulator II

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#156]
**Describe the bug**
While writing automated tests to determine if the Library networks loaded correctly, I cam across the issue that not all library networks can be loaded after all others. Clearest example is loading 3DSim after SimVision, which hangs Brain Simulator II so it has to be killed via task manager. 

**Application**: Brain Simulator

**Module/Network**: various networks, all combinations should work.

**To Reproduce**
1. Load Library => SimVision and click away the notes.
2. Load Library => 3DSim, and notice you can't click the notes away since cursor is now a cross-hair.
3. Notice Close Window from the taskbar fails.
4. Kill Brain Simulator from the task manager, because that is the only way to do so. 

**Expected behavior**
No matter what network was loaded first, any library network should load flawlessly.

**Screenshots**
![IMG_20210516_141727](https://user-images.githubusercontent.com/11266191/118397003-5a179300-b652-11eb-9053-fb109242d3f8.png)

**Desktop (please complete the following information):**
 - OS: Winodws 10 Pro 20H2
 - Version: 2021-05-16 master

**Comment by Moorelife** [comment]
CameraTest after Sallie has the same problem. Might it be a specific module that hangs the load?

**Comment by FutureAIGuru** [comment]
This is another “engine-is-running-when-it-shouldn’t” bug.
After a network is loaded the UKS must have its SetupAfterLoad method called prior to any Fire() call. I will investigate. The Fire methods of other modules make the reasonable assumption that if the UKS module exists, it has a reasonable data structure initialized, but in this case, it does not.

**Comment by FutureAIGuru** [comment]
This is now fixed and will check in soon. Here's the scenario so we can remember for the next time ☹
The "SAVE" dlg suspends the engine and opens.
When it closes, it sets the flag to resume the engine but does not wait for it to start.
The LoadFile() method then requests that the engine be suspended BUT it's too soon after the previous resume call and the engine hasn't resumed yet. The suspend request thinks the engine is already suspended so it does nothing and returns.
Now, the engine is running before the loadFile is complete and all kinds of unexpected results might occur.
SOLUTION: when resumeEngine or suspendEngine is called, these methods now wait until the engine thread has actually completed the task before returning.

**Comment by Moorelife** [comment]
This indeed is fixed.
