### ISSUE TITLE
When engine is stopped, clicking a neuron and then another neuron leaves the former 'gray'.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#159]
**Describe the bug**
When the engine is stopped, if you click a neuron it gets selected, and if you click another it remains grayish, instead of true blue like when the engine is running. 

**Application**: Brain Simulator

**Module/Network**: N/A

**To Reproduce**
1. Create a new network.
2. Start the engine.
3. Click a few neurons, see how each in turn gets selected, and returns to its normal blue color.
4. Stop the engine.
5. Click a few neurons and see how they each in turn get selected, but remain gray after the selection has jumped to the next one.

**Expected behavior**
In running mode I would expect the neuron to fire, but in stopped mode I merely wish to manipulate neurons, not mess with their charges unless I specifically ask for that. 

**Screenshots**
![IMG_20210517_154149](https://user-images.githubusercontent.com/11266191/118498599-7e44a400-b726-11eb-83b1-0ea8c90bf65e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version: 2021-05-17 master

**Comment by FutureAIGuru** [comment]
This isn't a bug, it's a feature. :)  If you want to fire five neurons at once, stop the engine, click the five neurons, they'll go gray, then when you step or start the engine, these five neurons will fire simultaneously. 

There was also a bug which I fixed which left neurons grayish when the engine was running.
