### ISSUE TITLE
Various modules crash the program upon insertion.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#164]
**Describe the bug**
During development of the automated tests for the module insert combobox, the following modules were found to be detrimental to the health of the program:

- module_boundary  # still crashes the program.
- module_chain  # still crashes the program.
- module_graph  # still crashes the program.
- module_motor  # still crashes the program.
	
**Application**: Brain Simulator

**Module/Network**: see above modules

**To Reproduce**
1. Create one of these modules.
2. See the program crash.

**Expected behavior**
Program should not crash but may issue a warning about needing another module.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Version [v0.9a]

**Comment by Moorelife** [comment]
In the case of Boundary, apparently an imagefile module is needed first.
In the case of Chain, the module can not be found yet in the neuron array, since it is in the process of being created.
In the case of Graph, something obscure happen in the Initialize that crashes things. 
In the case of Motor, the 2x2 size is insufficient for the labeled neurons.

**Comment by FutureAIGuru** [comment]
Don’t know about graph…

Chain needs a line if (na==null) return; to its onresize method

Boundary and Motor don’t respect their module’s size.

I’ll look into graph module. DO you want to look at these others or wait for me to get to it?

**Comment by Moorelife** [comment]
Motor module now works too.

**Comment by Moorelife** [comment]
I already fixed Motor, I guess Boundary is similar. I'll check Chain too

**Comment by Moorelife** [comment]
Well, it already crashes because there is no ImageFile module. I'll sleep on it and attempt some improvements tomorrow.

**Comment by Moorelife** [comment]
All of these issues have now been fixed.
