### ISSUE TITLE
Undo resize module does not resize it to previous size.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#168]
**Describe the bug**
Modules that are resized and for which ctrl-Z is pressed do not revert to their previous size. 

**Application**: Brain Simulator

**Module/Network**: All modules

**To Reproduce**
1. Create a camera module via the insert combo box on the toolbar.
2. Notice it is 2x2 size.
3. Enlarge it to 5x5 size.
4. Press ctrl-Z, notice size is not 2x2, but 2x3.

**Expected behavior**
If a resize is undone, it should be properly undone, and not be off by one... 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version: 2021-05-29 master

**Comment by FutureAIGuru** [comment]
This used to work…must have gotten broken with other changes.
