### ISSUE TITLE
Tool tips might be numbered too if applied to a whole selection.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#169]
**Is your feature request related to a problem? Please describe.**
#167 once and for all determined the correct way for a selection of neurons to be numbered. However, once this is done, and with another right-click the tool tip is entered to apply to the whole selection, then all neurons selected will have the same tool tip.

**Describe the solution you'd like**
It seems to me that if the labels are numbered, any tool tip set in that selection would also be numbered identical for consistency. 

**Describe alternatives you've considered**
1. if a neuron has a numbered label, also add the number to the tool tip before showing it. 
2. if a neuron has its tool tip text set (and applied to a whole selection), then auto-number them like we do the labels. 
3. decide that tool tips need no numbers in their labels, and leave it at that. 

**Additional context**
I can live with any of these options, I just would like the design choice to be resolved.

**Comment by FutureAIGuru** [comment]
I think that this already works OK. Neuron Labels ae auto-incremented but tooltips are replicated. Let’s close it.
