### ISSUE TITLE
Neurons now only show black and white, never other colors

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#173]
**Describe the bug**
Brain Simulator II used to show various colors for neurons depending on their charge level. The latest version only shows black and white on networks that previously showed many colors.

**Application**: Brain Simulator

**Module/Network**: N/A

**To Reproduce**
1. Open any previously saved network.
2. See it run in black and white rather than color.

**Expected behavior**
I expect the previous behavior, or some explanation why this was changed (is it a new feature?).

**Screenshots**
![20210614_123039](https://user-images.githubusercontent.com/11266191/121879515-3efd7900-cd0d-11eb-90fa-278275910756.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 2021-06-14 master

**Comment by FutureAIGuru** [comment]
![TempImage](https://user-images.githubusercontent.com/48232830/121911648-ce426680-cce4-11eb-9c79-aa389f44f7ac.png)
I don't see this problem either from my local dev or from the downloaded code.

**Comment by Moorelife** [comment]
![20210614_201436](https://user-images.githubusercontent.com/11266191/121940101-0762f100-cd4e-11eb-8f64-8bc6746ca233.png)
I've updated my Visual Studio to 16.10.1, but still have the above view of BasicNeurons from my dev environment AND from a ZIP file separately downloaded direct from Github 10 minutes ago. I am frankly baffled by this...

**Comment by Moorelife** [comment]
It seems RainbowColorFromValue() never receives values for lastcharge other than 0, -1 and 1. Still looking where the charge is calculated or set, but something must be wrong upstream.

**Comment by Moorelife** [comment]
The 'fault' turned out to be a new way Windows handles the locale settings, because my system had English display language but Dutch locale settings, which use a comma as the decimal point. Workaround is to make your system truly US English for both, after which the problem disappears. Since I did not recently adjust my settings myself, I figure Microsoft introduced a bug in one of their updates, and will fix it shortly....   So this bug can be lowered in priority and closed when they do.

**Comment by FutureAIGuru** [comment]
Congrats Andree-

I’m glad you found the issue…  ‘

I’m still puzzled. The process of copying a neuron leak rate float from a c++ dll to a c# .exe shouldn’t change it’s value. Your system should automatically write 0,05. That’s the point of saying (in GetNeuronLabel) n.leakrate.ToString().

When I get a chance, (in code) I’ll set my culture to dutch and see if I can replication your symptoms.

Cheers,
Charlie

**Comment by Moorelife** [comment]
This no longer occurs in the 20210720 master
