### ISSUE TITLE
Various paths for creation of Modules do not all give them the same consistent starting color.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#174]
**Describe the bug**
For automated testing it would be advantageous if all ways of creating a module created it with the same default color. 

**Application**: Brain Simulator

**Module/Network**: N/A

**To Reproduce**
1. Make a module from the toolbar: it shows AliceBlue.
2. Make a module by converting a selection: it shows Wheat.
3. Make a module from the edit menu: it shows AliceBlue. 

**Expected behavior**
I would expect all ways of making a module start with the same color.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 2021-06-20 master

**Comment by Moorelife** [comment]
Easily fixed....

**Comment by FutureAIGuru** [comment]
Thanks
