### ISSUE TITLE
Please make module behavior consistent no matter how they are created. 

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#176]
**Is your feature request related to a problem? Please describe.**
Recently added automated tests have shown there are differences in modules depending on which way they were created, which can be any of these creation paths:
1. Insert a module from the Edit => Insert Module menu entry.
2. Insert a module from the toolbar "Add Module" combobox.
3. Create a selection and convert it to a module from the Selection menu.

**Describe the solution you'd like**
Ideally, a newly created module should have a "minimal or optimal dimension" to present all labeled cells in the configuration required. If resized, it should not be able to size the module smaller than these dimensions. The "Move" module is a good example of such a module.

Automated tests revealed the following module types are NOT responding in this way:
- 3DSim.
- Arm. 
- ImageFile.
- Life.
- Motor.
- SpeakPhonemes.
- SpeakPhonemes2.
- StrokeCenter.
- StrokeFinder.
- UKS2.
- UKSN.

**Additional context**

**Comment by FutureAIGuru** [comment]
There is min/max ht/width in the base module…they just need to be set properly in the derived module classes then this issue should clear up. This could be done at the same time the long/short descriptions are removed as these are no longer used.

**Comment by Moorelife** [comment]
I know about these, and can add these changes. Will start work on it tonight.
