### ISSUE TITLE
Deleting a module which has a dialog open may leave it open

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#179]
**Describe the bug**
Deleting a module which has a dialog open may leave it open. If you delete from the context menu, it works properly. If you delete a module via a selection, the module is deleted but the dialog is left open.

**To Reproduce**
1. Add a module (ImageFile) to a network
2. Open the module dialog
3. Ctl-A to select all
4. Delete
5. Note that all the content of the network is removed but the dialog remains

**Expected behavior**
Dialog should be closed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Version [v0.9a]

**Comment by Moorelife** [comment]
Should be fixed with my single-line fix just completed....
