### ISSUE TITLE
File => Properties setting change is not persisted.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#29]
**Describe the bug**
Setting columns if File => Properties does not work as designed and mentioned in the CameraTest network description.

**Application**: Brain Simulator

**Module/Network**: CameraTest 

**To Reproduce**
1. Open File => Library => CameraTest network.
2. Open File => Properties as is suggested in the network description and set columns to 200.
3. Reopen File =>Properties and notice columns is still 100.
4. As a result, the second step (setting width and height) gives an error.

**Expected behavior**
I expect the program to actually set the columns to 200. 

**Screenshots**
![IMG_20210412_184728](https://user-images.githubusercontent.com/11266191/114431248-93766200-9bbf-11eb-84ec-74b94a32c59a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 1.0

**Comment by FutureAIGuru** [comment]
Actually, changing any value in the properties dialog doesn't do anything at all.  Shouldn't be too tough to handle increases in rows or columns but reduction would be difficult. The non-active fields in the properties box should all be disabled.

**Comment by Moorelife** [comment]
This now at least works for the column count as mentioned in the CameraTest network. I understand the update of specific values may not be as straightforward as that, since reducing the size of a network is a non-trivial issue.
