### ISSUE TITLE
Reloading CameraTest will give an error and leave the network in a non-workable state.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#30]
**Describe the bug**
Reloading CameraTest either through File => Open or File => Library will generate an error every time.

**Application**: Brain Simulator

**Module/Network**: CameraTest

**To Reproduce**
1. Open Network CameraTest either through File => Open or File => Library or File => Recent Files.
2. Try the same action a second time. 
3. Notice Graph Builder error presented. 
4. Brainsimulator II will leave camera window empty.
5. Restart of the program is required to clear this error!

**Expected behavior**
The CameraTest network should open without error messages, no matter what network has been opened before.

**Screenshots**
![IMG_20210412_185203](https://user-images.githubusercontent.com/11266191/114432965-8bb7bd00-9bc1-11eb-83e1-e69a4177f441.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro   20H2
 - Version v1.0

**Comment by FutureAIGuru** [comment]
I can replicate this bug.

**Comment by Moorelife** [comment]
Current Master has this problem fixed.
