### ISSUE TITLE
Off by one bug in firing sequence.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#32]
**Describe the bug**
There is an off-by-one bug in the neuron engine or the brain simulator, where the firing from one column to the next is concerned.

**Application**: Brain Simulator, Neuron Engine

**Module/Network**:  ZIP file of XML file added, because XML is not allowed by Github. 
[off_by_one.zip](https://github.com/FutureAIGuru/BrainSimII/files/6299056/off_by_one.zip)

**To Reproduce**
1. open the attached off_by_one.xml file.
2. notice it links one row and one column to the top-left neuron (all with 1.0 weights).
3. Click the top-left neuron to make it fire continuously.
4. Notice the downward line completes, but the left-right line misses the last firing.

**Expected behavior**
I expect even the last column to properly be reached. 

**Screenshots**
![IMG_20210412_204716](https://user-images.githubusercontent.com/11266191/114445400-51a1e780-9bd0-11eb-908f-cb87e564cef7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 1.0

**Comment by FutureAIGuru** [comment]
In this example, any neurons with IDs > 127 don't fire. Suspect that part of the engine requires that the neuron array be a multiple of 64 in size. Internally, this 144-neuron array should have 192 neurons instead of 128.

**Comment by Moorelife** [comment]
Current master shows this fixed.
