### ISSUE TITLE
Use servers in New Network detects no servers.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#38]
**Describe the bug**
Brain Simulator does not see any servers in new network dialog.

**Application**: Brain Simulator, Neuron Server

**Module/Network**: N/A

**To Reproduce**
1. Take two computers on the same local network.
2. Start a server on system #1.
3. Start the brain simulator on system #2.
4. Choose New Network.
5. Check 'Use Servers'.
6. Notice 'no servers detected'.
7. When done with only one computer, the results are the same.

**Expected behavior**
If a neuron server is running on a local network, it should be visible in the use servers list when 'use servers' is checked.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 1.0

**Comment by Moorelife** [comment]
Actually, the checking of the use servers checkbox in my case already brings up a request for the allowing of the firewall setting in the windows firewall. After that it should work fine if refresh is clicked, but that does not seem to work. 
![IMG_20210415_112122](https://user-images.githubusercontent.com/11266191/114846552-1b858300-9ddd-11eb-998a-039b1260d6f0.png)

**Comment by FutureAIGuru** [comment]
You must make an identical firewall entry on the server machine. Did you try that?
Charlie

**Comment by Moorelife** [comment]
Hi Charlie,

For now I went with the idea that it would be possible to run both brain simulator and a neuronserver on one machine, but my setting should warn me whenever a firewall rule is required that is not there yet.

**Comment by wolviey** [comment]
Also some switches block broadcasting , just for detail, could be nice to server scan ip with ports or possible to add ip:port

**Comment by FutureAIGuru** [comment]
I just found a way to punch through the firewall programmatically. The sample doesn’t work but I will investigate further.
https://doumer.me/allow-your-app-through-the-firewall-with-c/

**Comment by Moorelife** [comment]
This has now officially been solved.
