### ISSUE TITLE
Quick open of BrainSim II XML files via "Open With"

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#40]
**Is your feature request related to a problem? Please describe.**
Because of the experimental nature of the BrainSim II program, and its use of XML files to store networks, a more speedy way to open them could be via the "Open With" in the right-click menu of Windows Explorer. 

**Describe the solution you'd like**
Obviously you wouldn't want to open all XML file with the BrainSim II program of course, so one might consider the following:
1. Give BrainSim II XML files their own distinct extension (like B2XML), but keep the XML format of the files.
2. This allows for "Open With" to be set for the Brain Simulator II program so double-clicking a B2XML file opens it.
3. When the installer issue is fixed, this file association can be set as default. 
4. The right-click menu can then still be used to op the B2XML files in say Notepad++.

**Describe alternatives you've considered**
Currently I can try to open the XML file with BrainSim II, but the file is never loaded...

**Additional context**

**Comment by FutureAIGuru** [comment]
I think this requires a registry entry which would be part of the installer. https://docs.microsoft.com/en-us/windows/win32/shell/how-to-include-an-application-on-the-open-with-dialog-box

**Comment by Moorelife** [comment]
That indeed is one way of doing it, although the user can add any program by browsing for it. But I will have a look at it tomorrowOn Apr 21, 2021 20:11, Charles Simon ***@***.***> wrote:
I think this requires a registry entry which would be part of the installer. https://docs.microsoft.com/en-us/windows/win32/shell/how-to-include-an-application-on-the-open-with-dialog-box

**Comment by Moorelife** [comment]
The registry entry is no problem, I can do that right now. What fails however is this:
If I call Brain Simulator II.exe with an XML filename, it does not (as expected) load the requested file,
but stubbornly sticks to loading the previously loaded file. 
Normal convention for dragging and dropping files on a program make it so you get the file specification as argument 1 in your main function.

**Comment by FutureAIGuru** [comment]
The program needs to be modified to accept a startup argument.  No Problem.
Charlie

**Comment by FutureAIGuru** [comment]
I uploaded a fix which reads a filepath as the first startup arg. If it is omitted, the program will reload whatever was being edited last. If that doesn’t exist, a new network will be created by default.

**Comment by Moorelife** [comment]
It now works almost great! I added the file association and can now just double-click an XML file.
However, the open crashes if the XML file is not a valid BrainSimII file. 
Any chance you can make that a bit more graceful by checking for the 
<NeuronArray xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
tag, and avoiding the loading of the file instead just opening a message box and then loading the last active one? 
Better than this:
![IMG_20210424_082320](https://user-images.githubusercontent.com/11266191/115949692-0b555e00-a4d7-11eb-9105-a16e135532ee.png)

**Comment by Moorelife** [comment]
last minor issue fixed.
