### ISSUE TITLE
Clicking on any context menu outside of a specific control cancels the context menu

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#47]
**Describe the bug**
Clicking outside a specific control on a context menu closes the context menu and loses changes

BrainSim

**To Reproduce**
1. Right-click a neuron
2. On the context menu, click to the left of the ID
3. The context menu closes

**Expected behavior**
The context menu should remain open 

 - OS: Win10
 - Version [v0.9b]

**Comment by Moorelife** [comment]
Works fine in the 2021-04-15 #2 master
