### ISSUE TITLE
Paste Here sometimes crashes the Brain Simulator program

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#48]
**Describe the bug**
Although Move Here does not show this behaviour, Copy Here CAN crash the Brain Simulator in some cases. 

**Application**: Brain Simulator

**Module/Network**: BasicNetwork

**To Reproduce**
1. Open the BasicNetwork.
2. Select the network in the first image below and click Copy.
3. Select the neuron in the free area so the paste would fit.
4. Click Paste Here, network gets pasted. (=OK)
5. Select the network in the second image below and click Copy.
6. Select the neuron in the free area so the paste would fit.
7. Click Paste Here, Brain Simulator crashes without warning.

****
**Expected behavior**
Obviously crashing is out of the question, but I would be content if a message said WHY the copy is not allowed.
Or better yet, fix the problem so the copy does succeed.

**Screenshots**
Network that does copy ok:
![IMG_20210414_070323](https://user-images.githubusercontent.com/11266191/114659853-9b83ee00-9cf4-11eb-96ca-e644ec03032a.png)

Network that crashes the program:
![IMG_20210414_070042](https://user-images.githubusercontent.com/11266191/114659885-a8084680-9cf4-11eb-8523-475db9ceab77.png)

Event Viewer info on the problem:
[event viewer output.txt](https://github.com/FutureAIGuru/BrainSimII/files/6308409/event.viewer.output.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 2021-04-13  master

**Comment by FutureAIGuru** [comment]
Fixed...checked in doon

**Comment by Moorelife** [comment]
Hi Charlie,

When building the code just now I noticed a warning that could easily be removed:


Change the red part of the line of code, and you have just 2 warnings left... :-)

Going to test the latest and greatest now!


Best Regards,

André

**Comment by FutureAIGuru** [comment]
Great Stuff!
I’m in the middle of changing the way text input works in order to get validation. I should have that and a bunch of other less-difficult items checked in by tomorrow.
Charlie

**Comment by Moorelife** [comment]
Hi Charlie,

I've been playing all night, among other things trying to get a seven segment digital clock working. Having one digit counting up was easy, but the carry to the next digit is giving me a bit of a headache. I've added it to this mail.

One feature request I haven't added yet is making the OK button default to work along with the tab order, so you can operate the popup menus from the keyboard alone. Very normal in GUI design, but it may be less fun to program than the actual brainsim work... :-)

For now I'm done, gonna hit the shower and turn in.

Looking forward to your next update.

By the way, do you already have some command file to copy the required files into the ZIP file structure from the built project? If not I might spend some time there to create one. Or maybe even start on writing an installer script.


Best Regards,

André

**Comment by Moorelife** [comment]
Works fine in the 2021-04-15 #2 master
