### ISSUE TITLE
Please add dragging of selection to minimize actions for move.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#51]
**Is your feature request related to a problem? Please describe.**
Being somewhat of a power-user, it vexes me to have to perform the following action in order to move (part of) a network:
1. select an area.
2. right-click the area.
3. select Copy from the menu.
4. right-click the destination top-left destination neuron.
5. select Move Here from the menu.

**Describe the solution you'd like**
These five steps could be simplified as follows:
1. select an area.
2. move the mouse over it, cursor becomes grabbing hand.
3. drag the selection to its new location.

**Describe alternatives you've considered**
This can be done in several ways:
- show only the rectangle as it is dragged.
- show the rectangle and its links to other neurons outside the selection.
- if dragged with left mouse button, consider it always a move.
- if dragged with right mouse button, show a popup menu before drop so user can choose to move or copy.
- the menu can also have options to copy 'attached', or copy 'detached' with regard to the original network.
- selection should of course move too, so what was selected is now selected in the target position.

**Additional context**

**Comment by Moorelife** [comment]
the 2021-04-15 master contains a nice first attempt, but it has a few flaws:
1. The drag sometimes suffers from 'premature drop' if the drag path hits an occupied neuron. This evaluation of the overwriting should not cause the drop, but should be evaluated once the drop is done. If the user confirms, drop it on the new target, if the user declines, leave it in its original position. 
2. The undo mechanism should only concern itself with the source and target positions, and not all intermediary positions. Now I need to press undo as many times as the steps involved in getting from target back to source.
3. When doing undo steps after a move, the selected network moves back, but the selection stays in the target position.
4. When dragging the selection to a position that would take it outside of the network range, a debug assertion is triggered. This should be properly handled by refusing to move the selection in this direction.

**Comment by FutureAIGuru** [comment]
I have fixed items 2 & 3.
For your 4, I got a messagebox which now doesn’t show if you are dragging. It still shows if you use the “Move Here” so at least you know why the Move Here didn’t do anything..
Your item 1 would be a big deal because the MOVE, as written, doesn’t use the clipboard.  I added a line to the messageBox to suggest how you can move the selection directly to a destination. I added this as Issue 57 so you can close issue #51 if your satisfied with the parts which work.
Charlie

**Comment by Moorelife** [comment]
Confirmed: 2 & 3 are fixed, but 4 remains:
with "Copy" and "Move Here" it is only possible to get the error box when moving too close to right or bottom boundary.
with drag and drop, it is possible to get it on all four sides, but it only happens on Top, Right and Bottom.
when dragging to the left boundary, and then crossing it, the following debug assertion still triggers:
![IMG_20210415_190634](https://user-images.githubusercontent.com/11266191/114910611-65428d80-9e1e-11eb-8daa-d609cd9f4f99.png)

**Comment by Moorelife** [comment]
Will tackle any other bugs in drag & drop as they occur, closing this request for a job well done.

**Comment by FutureAIGuru** [comment]
Oops, I didn’t check the left side or top.
