### ISSUE TITLE
Increasing usefullness of Spiking History Window

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#52]
**Is your feature request related to a problem? Please describe.**
The Spiking History window appears to have a scrollbar, but it is non-functional. 
As a results the timeline fills the window until it is a big black mess without any detail.
Clearing the window then kills ALL history, and you have to start from scratch.
In addition there is the double close button, where the one on the window title bar only closes it, and the one in the window sets all view firing history channels to off.

**Describe the solution you'd like**
1. I'd like the Spiking History shown to compress no further than 1 cycle per 4 pixels, so spikes remain visible.
2. After that, just show the end of the timeline, and if possible keep further history up to a certain maximum stored off-screen.
3. Scroll bar should show the ration of shown to stored timeline, and remain on the right side.
4. If the scroll bar is moved, show the relevant portion of the timeline in the window as the scrollbar is moving.
5. If needed, add a button to go back to the trailing end of the graph.

**Describe alternatives you've considered**

**Additional context**

**Comment by FutureAIGuru** [comment]
There is a UI issue that the mouse wheel zooms in and out on the history display.  This needs to be emphasized. 
THEN, there is the change from your issue #39 which must limit the number of samples collected.
FINALLY, your suggestion 2 is a good one.

**Comment by Moorelife** [comment]
True, your mention of the scroll wheel solves 3, 4, and 5. Matter of not RTFM on my side.

**Comment by Moorelife** [comment]
Nicely fixed in the 2021-04-17 master.
