### ISSUE TITLE
Dragging a selection over existing neurons should be allowed

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#57]
**Is your feature request related to a problem? Please describe.**
If you are dragging a selection and it crosses any used neurons, the drag is stopped with a messagebox. If you respond OK to the messagebox, the content of the neuron array is clobbered.

**Describe the solution you'd like**
Dragging should be allowed across in-use neurons and only checked at a destination location.

**Describe alternatives you've considered**

**Additional context**

**Comment by Moorelife** [comment]
The current implementation of drag and drop module does not easily allow for a module to be dragged over an existing neurons, so instead an extra tip was added to the message showing how move is more easily achieved using 'select' and 'move here'.
