### ISSUE TITLE
When creating a new Network, the Use Servers checkbox doesn't enable the related buttons

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#58]
**Describe the bug**
When creating a new Network, the Use Servers checkbox doesn't enable the related buttons\

**Comment by Moorelife** [comment]
I noticed the grayed buttons, but figured that was still a work in progress.... :-)

**Comment by Moorelife** [comment]
Despite the mention this should be fixed, I still see "No Servers Detected" and the grayed buttons Refresh and Speed Test
