### ISSUE TITLE
Make sure previous network has been freed before starting estimate for new network

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#62]
**Describe the bug**
When I have a sizeable network in memory, and decide to create a new one, the free memory estimate is far too low.

**Application**: Brain Simulator, Neuron Engine

**Module/Network**: New Network

**To Reproduce**
1. Start a New Network. I noticed 45 million neurons estimated capacity.
2. Cancel it when it is a few minutes in, this still leaves a partially filled network (should not remain, I canceled).
3. Start New Network again, notice the "do you want to save, answer 'no'.
4. New Network dialog comes up but the max estimated capacity is now under 30 million neurons. 

**Expected behavior**
I expect the previous network to be completely deallocated before new network is starting its estimate. This may be difficult since C# is garbage-collecting, but a quick and dirty fix would be to just shutdown and restart brain simulator, because then Windows frees the memory. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 2021-04-15 master
 
Notice how the old network is still shown in brain simulator while the new one is already being created:
![IMG_20210415_203507](https://user-images.githubusercontent.com/11266191/114920955-4ba74300-9e2a-11eb-9d18-b76a6f8a430c.png)

**Comment by FutureAIGuru** [comment]
A more inconvenient problem is that if you Cancel from the New Neuron Array dialog, you'd like the old network to still be there. Perhaps we could just estimate the size of the old network and add it in to the free memory.

**Comment by Moorelife** [comment]
Hi Charles,

I see the following logic here:
- If the user said NOT to save the old network, he or she is not interested in keeping it.
- If the user said to save the old network, we can simply reload it if a new network is canceled halfway.
- Either way, there is no need to keep the old network in memory while a new one is being built.

**Comment by Moorelife** [comment]
Since the new network function now only assigns a neuron array,  and no longer also handles the random synapses, I will fix this.

**Comment by Moorelife** [comment]
Has been taken care of.
