### ISSUE TITLE
New Network crashes brain simulator if previous New Network was canceled.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#65]
**Describe the bug**
It may seem far-fetched, but consider this situation: 
a user starts a new network, then decides the start parameters were wrong, cancels it and redoes it, and BOOM!

**Application**: Brain Simulator, Neuron Engine

**Module/Network**: New Network

**To Reproduce**
1. Start a new network, 150x300, 100 random synapses.
2. When the progress bar has taken a few steps, cancel it. 
3. Neuron window shows a partial initialized network.
4. Restart New Network, 1500x3000, no random synapses (doesn't matter).
5. Brain Simulator crashes. 

**Expected behavior**
Proper handling of the uncaught exception, so we can recover or at least gracefully shut down. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 2021-04-16 master

Event message found because of this:
[unhandled exception.txt](https://github.com/FutureAIGuru/BrainSimII/files/6326414/unhandled.exception.txt)

**Comment by FutureAIGuru** [comment]
I think this is no longer an issue. Random synapses has been moved to a selection. You want full random synapses? Ctl-A to select the whole network.  Because the creation of synapses was the slow part, there is no longer a progress bar to cancel.

**Comment by Moorelife** [comment]
Yup, fixed.
