### ISSUE TITLE
Engine crashes on dragging selection, with engine running.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#70]
**Describe the bug**
When dragging a selection while the neuron engine is running, the program is decidedly more prone to crashing, with the general try/catch not displaying an error. 

**Application**: Brain Simulator, Neuron Engine

**Module/Network**: See attached 
[seven segment.zip](https://github.com/FutureAIGuru/BrainSimII/files/6329078/seven.segment.zip)

**To Reproduce**
1. Start the release version of brain simulator.
2. Load the network and stop the engine. 
3. Grab a single neuron selection like D9.
4. Drag it across empty neurons.
5. See drag and drop succeed.
6. Now start the engine.
7. Watch the program crash within a few seconds!
8. If you didn't stop the engine before dragging the same happens mid-drag.
9. No Exception message, so it is probably a neuron engine problem. 

**Expected behavior**
I would already be happy if live dragging would be avoided, by stopping the engine before drag and restarting it.
Nicer solution would be to avoid the crash altogether and allow for the engine to be live while dragging.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 2021-04-17 master

**Comment by FutureAIGuru** [comment]
I could not duplicate this. Are you doing this in a specific network? Are there modules involved?

**Comment by Moorelife** [comment]
I did it with the attached network described in the text, but now can also no longer replicate the bug. Considering it fixed.
