### ISSUE TITLE
Scaling with selection present makes weird redraw on section boundary.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#73]
**Describe the bug**
When zooming out the view from colored squares to numbered sections with an active selection present, there is still drawing of colored squares that lasts all the way up to the colored squares occupying almost a single pixel, then the program crashes. 

**Application**: Brain Simulator

**Module/Network**: Random synapses new network.

**To Reproduce**
1. Start a new network with random synapses.
2. Create a steady drive by linking two neurons to themselves and each other with +1 synapses.
3. Set a selection for part of the network.
2. Zoom out, up until the smallest possible colored squares.
3. Zoom out further, notice that view goes to "section view", and everything outside the selection is no longer drawn.
4. The selection however is still drawn (= BUG1)
5. Further zooming out the drawing continues, until the selection is as small as a single pixel on screen.
6. Zooming one step further then causes this exception:

![IMG_20210417_135515](https://user-images.githubusercontent.com/11266191/115112481-04ce6000-9f86-11eb-9409-365a9fa52697.png)

**Expected behavior**
I would expect a clean break from drawing colored squares to just numbered sections. So:
- No drawing of the current neuron in section view.
- No drawing of live neurons in case of a selection.
- Possibly put the section number closer to the top left of the section, especially when section is way larger than network. 
- And basically, zooming out beyond the Zoom All position seems pretty useless... 

**Screenshots**
Section view showing current neuron, selection area and section number. 
![IMG_20210417_140845](https://user-images.githubusercontent.com/11266191/115112659-d1d89c00-9f86-11eb-8e48-9e2173bcd13d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 2021-04-17 master

**Comment by FutureAIGuru** [comment]
Your bug #1 as step z6 is actually a feature. When things are too small to see, you can just to a selection and see an area.

**Comment by Moorelife** [comment]
OK, closing this then.
