### ISSUE TITLE
After using the installer to install, uninstall doesn't work

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#78]
**Describe the bug**
After an uninstall, the program is removed from the add/remove programs list but is still present in ProgramFiles/FutureAI and sill shows up on the start menu.

**Application**: Installer

**To Reproduce**
1. Build  self-extracting brainsim.exe
2. run it, program installs properly
3. select Add/Remove programs and uninstall brain simulator
4. program is still in the programfiles/futureai folder and still on the start menu

**Expected behavior**
uninstall should be complete

**Desktop (please complete the following information):**
 - OS: Wind10 20H2
 - Version [v0.9c+]

**Comment by Moorelife** [comment]
Guess that is my first point to look into.... :-)

**Comment by Moorelife** [comment]
Problem solved, and sent in via E-mail....
