### ISSUE TITLE
Copy to new network is counter-intuitive.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#80]
**Is your feature request related to a problem? Please describe.**
The Guide says I can copy parts of networks to a new network on their own.
I have tried these approaches, some of which work and some not:
1. Select & copy a part of a network and attempt to paste it in another instance of Brain Simulator. No shared buffer, so no copy.
2. Select & copy a part of a network, then select all and press delete, then paste. Copy is there, but network still has the old name.
3. Select & copy a part of a network, then make a new empty network and paste there. This works, but no longer shows the synapses as the neurons have their "show synapses" removed. 

**Describe the solution you'd like**
I would love an additional entry in the selection popup menu that says "Create New Network from Selection".
Slight problem is I may want to be able to give a new dimension for the network.
So maybe select the relevant part, then select New Network and have a "copy from selection" checkbox there?

**Describe alternatives you've considered**
Of course the option 3 above also works, if you do a save as immediately following it. 

**Additional context**

**Comment by Moorelife** [comment]
I cannot verify point 1 as fixed: select and copy in one instance works, but then for the second instance of the program paste here is disabled.

**Comment by FutureAIGuru** [comment]
My bad, it’s your item 2 which is fixed.

**Comment by FutureAIGuru** [comment]
Your original items 1 & 3 are still open

**Comment by FutureAIGuru** [comment]
This has been substantially changed.  It doesn't do precisely desired solution but it may achieve your overall objective.

**Comment by Moorelife** [comment]
I will check it out and close this, but i indeed think using the windows clipboard is a great improvement already.

**Comment by Moorelife** [comment]
If from that we can also paste it into any copy of Brain Simulator II that is great....

**Comment by FutureAIGuru** [comment]
Yes, copy/paste from one instance of BrainSim to another seems to work.

**Comment by Moorelife** [comment]
The new changes are sufficient to do what I want.
