### ISSUE TITLE
ModuleCamera should remove synapses first.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#90]
**Describe the bug**
When synapses are present in the area where a ModuleCamera is created, the synapses remain.

**Application**: Brain Simulator

**Module/Network**: ModuleCamera, or modules in general.

**To Reproduce**
1. Create a default network with random synapses.
2. Select the All Synapses checkbox.
3. Press Ctrl-A to select all neurons.
4. Right-Click and make all a ModuleCamera.
5. Notice Synapses are still shown, but serve no purpose anymore.

**Expected behavior**
The following preparation should be present for creation of a module (any module):

1. if any cell of the area to be made a module is part of another module, creation should be confirmed.
2. if confirmed, a module hit by the new module should be removed.
2. neurons should be returned to their initial status.
2. synapses connecting the cells, and entering or leaving the area should be removed.

**Screenshots**
![IMG_20210420_140848](https://user-images.githubusercontent.com/11266191/115393438-fc726100-a1e1-11eb-95df-d7a0c0c67b6d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version: 2021-04-20 master

**Comment by FutureAIGuru** [comment]
This is true of all modules.  Easily fixed.

**Comment by Moorelife** [comment]
Actually not fixed yet....
![IMG_20210423_083545](https://user-images.githubusercontent.com/11266191/115829190-f6ad9300-a40e-11eb-9937-bf6a78ba9b2f.png)

**Comment by Moorelife** [comment]
Fixed
