### ISSUE TITLE
Library Networks not properly handled.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#91]
**Is your feature request related to a problem? Please describe.**
Currently the installer puts the networks in the folder Networks in the installation directory (typically C:\Program Files\FutureAI\Brain Simulator II). However, since these files are opened to read and write, Windows denies access to them. Also it is a nuisance if the example networks somehow become changed by inadvertent saving.

**Describe the solution you'd like**
The clearest solution to this conundrum is the following:
1. if the path of the file to open contains "C:\Program Files", open the file for reading only.
2. make sure the filename is NOT set as would be true of a newly created network.
3. when the user wishes to save, ask the user for a filename.
4. any files not containing the above string can be opened like they are now. 

**Describe alternatives you've considered**
The above would fix both my "problems".

**Additional context**

**Comment by FutureAIGuru** [comment]
It is easy to put this in a dialog box like the installation location for the .exe file?

**Comment by Moorelife** [comment]
I could, yeah, but that would not solve the problem of keeping your example files intact. The user could still overwrite them accidentally.

**Comment by Moorelife** [comment]
Can be closed when the new handling of read-only files is in.
