### ISSUE TITLE
Please make random neurons a separate function.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#92]
**Is your feature request related to a problem? Please describe.**
I see three possible problems with "random synapses":
1. I can only select it for the whole network.
2. Random synapses make progress highly 'non-linear' in progress.
3. Distribution is definitely NOT random! (see screenshot 1)

I believe this happens mostly because the random neurons are created while each neuron is added. So any neuron added earlier in the cycle only fires out to those neurons already existing. 

**Describe the solution you'd like**
My preferred solution would be:
1. If 'random synapses' is to be an option in the new network dialog, at least do the creation in two phases
   (Neurons creation first, then synapse creation)
2. mark the progress per phase, so the user's impression of progress becomes more linear.
3. have 'random synapses' also as an option in the selection popup menu.

**Describe alternatives you've considered**
I believe this change would  alleviate all three possible problems.

**Additional context**
Non-randomness of neurons:
![IMG_20210420_143638](https://user-images.githubusercontent.com/11266191/115398105-16627280-a1e7-11eb-8bb3-9480214a020c.png)

New Network dialog after change:
![new network](https://user-images.githubusercontent.com/11266191/115398492-7fe28100-a1e7-11eb-83a1-c6d94dd512ce.jpg)

New selection popup menu:
![selection random synapses](https://user-images.githubusercontent.com/11266191/115398951-f54e5180-a1e7-11eb-9016-dceca469e1f9.jpg)

**Comment by FutureAIGuru** [comment]
Duh! Why didn’t I think of this?
Your issue 3 is an artifact of the synapse display limit. I guess we need to put up a warning. Perhaps in a status bar at the bottom?

**Comment by Moorelife** [comment]
Very nicely implemented.
