### ISSUE TITLE
Module2DSim crashes on 'Set Model'

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#93]
**Describe the bug**
It may be improper usage of the model, but I am able to crash BrainSimII on a Set Model.

**Application**: Brain Simulator

**Module/Network**: Module2DSim

**To Reproduce**
1. Create a Module2DSim.
2. Open the dialog.
3. Draw a synapse in the module.
4. Click 'Set Model'.
5. Notice crash dialog.

**Expected behavior**
Maybe I missed something I should have done, but I expected to see the synapse reflected as a barrier in the world of the dialog.

**Screenshots**
![IMG_20210420_172110](https://user-images.githubusercontent.com/11266191/115423026-c17e2680-a1fd-11eb-8cab-14d9b89dde8c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 2021-04-20 master

**Comment by FutureAIGuru** [comment]
If there is no 2dModel module, it failed.  Now, it will do nothing.

**Comment by Moorelife** [comment]
No longer crashes
