### ISSUE TITLE
Show Arcs checkbox in Module2DSim dialog seems to be unresponsive

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#94]
**Describe the bug**
The checkbox in the dialog of Module2DSim shows no arcs if checked, and also no warning as to why they are not showing.

**Application**: Brain Simulator

**Module/Network**: Module2DSim

**To Reproduce**
1. Create a Module2DSim.
2. Show its dialog.
3. Check the 'Show Arcs' checkbox.
4. Notice no arcs are shown.
5. Did I miss any prerequisites for them to show?

**Expected behavior**
I expected the vision arcs to show like they do on the Sallie Network.

**Screenshots**
![IMG_20210420_173845](https://user-images.githubusercontent.com/11266191/115424776-49186500-a1ff-11eb-9d62-951326c5db3d.png)

**Desktop (please complete the following information):**
 - OS: Winodws 10 Pro  20H2
 - Version: 2021-04-20 master

**Comment by FutureAIGuru** [comment]
This is a bug (ette). The arcs are displayed from the Vision process. If there is no 2dVision Module, there will be no arcs.  There should be a warning.
